[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"